version: "3.8"
services:
  tsna-server:
    image: registry-medialab.afp.com/tsna-server:0.3
    restart: on-failure
    container_name: tsna-server
    networks:
      - i18n-net
    ports: 
      - 8090:3000
    environment:
      REACT_APP_ELK_URL: ${REACT_APP_ELK_URL}
      REACT_APP_ES_USER_URL: ${REACT_APP_ES_USER_URL}
      # If Elasticsearch requires basic authentication:
      #REACT_APP_ES_USERNAME: ${REACT_APP_ES_USERNAME}
      #REACT_APP_ES_PASSWORD: ${REACT_APP_ES_PASSWORD}
      REACT_APP_AUTH_BASE_URL: ${REACT_APP_AUTH_BASE_URL}
      REACT_APP_I18N_CONTENT: ${REACT_APP_I18N_CONTENT}
      REACT_APP_GEXF_GENERATOR_URL: ${REACT_APP_GEXF_GENERATOR_URL}
      REACT_APP_GEXF_ES_BASE_URL: ${REACT_APP_GEXF_ES_BASE_URL}
      REACT_APP_MY_WEB_HOOK_URL: ${REACT_APP_MY_WEB_HOOK_URL}
      REACT_APP_GATE_CREDIBILITY: ${REACT_APP_GATE_CREDIBILITY}
      REACT_APP_GATE_CREDIBILITY_AUTH: ${REACT_APP_GATE_CREDIBILITY_AUTH}
      REACT_APP_GOOGLE_ANALYTICS_KEY: ${REACT_APP_GOOGLE_ANALYTICS_KEY}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}
      TWITTER_CALL_BACK_URL: ${TWITTER_CALL_BACK_URL}

      #REACT_APP_BASE_DOC: ${REACT_APP_BASE_DOC}
  tsv-server:
    image: nginx:latest
    restart: on-failure
    container_name: tsv-server
    networks:
      - i18n-net
    ports: 
      - 8001:80
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${TSV_SRV_LOCATION_PATH}:/www/data
networks:
  i18n-net:
