export const CT_SNA_CLEAN = "CT_SNA_CLEAN_STATE";
export const CT_COUNT_SET_RESULTS = "SET_CT_COUNT_RESULTS";
export const CT_HISTOGRAM_SET_RESULTS = "SET_CT_HISTOGRAM_RESULTS";
export const CT_PIECHART_SET_RESULTS = "SET_CT_PIECHART_RESULTS";
export const CT_IS_LOADING = "CT_IS_LOADING";
export const CT_PARSING_RESULT = "CT_PARSING_RESULT";
export const CT_HISTOVIEW_RESULT = "CT_HISTOVIEW_RESULTS";
export const CT_PIE_CHART_RESULT = "SET_CT_PIE_CHART_RESULT";
export const CT_BUBBLE_CHART_RESULT = "SET_CT_BUBBLE_CHART_RESULT";
export const CT_SNA_USER_PROFILE_MOST_ACTIVE =
  "CT_SNA_USER_PROFILE_MOST_ACTIVE";
export const CT_SET_HEAP_MAP_RESULT = "SET_HEAP_MAP_RESULT";
export const SET_CT_SNA_BUBBLE_CHART_RESULTS =
  "SET_CT_SNA_BUBBLE_CHART_RESULTS";
export const SET_CT_SNA_HEATMAP_RESULTS = "SET_CT_SNA_HEATMAP_RESULTS";
export const SET_HEAT_MAP_RESULT = "SET_HEAT_MAP_RESULT";
export const SET_CT_COHASHTAG_RESULTS = "SET_CT_COHASHTAG_RESULTS";
export const SET_CT_URLS_RESULTS = "SET_CT_URLS_RESULTS";
export const SET_CT_SNA_SOCIO_GRAPH_RESULTS = "SET_CT_SNA_SOCIO_GRAPH_RESULTS";
export const SET_HASHTAG_GRAPH_RESULT = "SET_HASHTAG_GRAPH_RESULT";
export const SET_CT_SNA_CLOUD_WORDS_RESULTS = "SET_CT_SNA_CLOUD_WORDS_RESULTS";
export const CT_PROCESS_MAX_STAGE = "CT_PROCESS_MAX_STAGE";
export const CT_PROCESS_STAGE = "CT_PROCESS_STAGE";
