export const CSV_SNA_CLEAN = "CSV_SNA_CLEAN_STATE";
export const CSV_SNA_SET_RESULTS = "SET_CSV_SNA_RESULTS";
export const CSV_COUNT_SET_RESULTS = "SET_CSV_COUNT_RESULTS";
export const CSV_SNA_SET_TYPE = "SET_CSV_SNA_TYPE";
export const CSV_HISTOGRAM_SET_RESULTS = "SET_CSV_HISTOGRAM_RESULTS"



export const SET_CSV_SNA_LOADING = "SET_CSV_SNA_LOADING";