export const TSNA_PROCESS_MAX_STAGE = "TSNA_PROCESS_MAX_STAGE";
export const SET_TWITTER_SNA_NEW_REQUEST = "SET_TWITTER_SNA_NEW_REQUEST";
export const SET_TWITTER_SNA_RESULT = "SET_TWITTER_SNA_RESULT";
export const SET_TWITTER_SNA_HEATMAP_RESULTS =
  "SET_TWITTER_SNA_HEATMAP_RESULTS";
export const SET_TWITTER_COHASHTAG_RESULTS = "SET_TWITTER_COHASHTAG_RESULTS";
export const SET_TWITTER_SNA_SOCIO_GRAPH_RESULTS =
  "SET_TWITTER_SNA_SOCIO_GRAPH_RESULTS";
export const SET_TWITTER_SNA_USER_PROFILE_MOST_ACTIVE =
  "SET_TWITTER_SNA_USER_PROFILE_MOST_ACTIVE";
export const SET_TWITTER_URLS_RESULTS = "SET_TWITTER_URLS_RESULTS";
export const SET_TWITTER_SNA_CLOUD_WORDS_RESULTS =
  "SET_TWITTER_SNA_CLOUD_WORDS_RESULTS";
export const SET_TWITTER_SNA_LOADING = "SET_TWITTER_SNA_LOADING";
